"""add review

Revision ID: dba533df02e6
Revises: bf62dc7bff81
Create Date: 2024-07-19 23:14:34.194588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dba533df02e6'
down_revision = 'bf62dc7bff81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_reviews_costumer_id_customers', 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('fk_reviews_customer_id_customers'), 'reviews', 'customers', ['customer_id'], ['id'])
    op.drop_column('reviews', 'costumer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('costumer_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(op.f('fk_reviews_customer_id_customers'), 'reviews', type_='foreignkey')
    op.create_foreign_key('fk_reviews_costumer_id_customers', 'reviews', 'customers', ['costumer_id'], ['id'])
    op.drop_column('reviews', 'customer_id')
    # ### end Alembic commands ###
